# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e9e5c1bc39f680c3942c243e67dcae21a99079278d0f3c09c98d023899e042a971de0e3b8401e2c06de125c17d09e4b95cdb90dfcda852a3a207862e177e31c

test:
  secret_key_base: 906a17a5173bc5307531a2057a0ee287e9f59fc2449a35742545110b8ce994b9418d67b314a340fa109b0216c700ea2790a70689195dc57c3e8bb446fd76a535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
